### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by tellfa** [zzhoujay/LowPolyAndroid#1]
Hi, thanks for this project
How can i use this project?

**Comment by zzhoujay** [comment]
首先，不推荐使用Android版的这个算法（在Android设备上效率极低，一张图大约需要80秒），如果实在是需要使用，将lowpoly这个module导入到你的工程即可。

推荐使用[这个库](https://github.com/zzhoujay/LowPoly) 在服务端生成后返回给android端

**Comment by tellfa** [comment]
can you send English? i can't speak china

**Comment by zzhoujay** [comment]
My English is not very good, the following is the translation of translation software:

First of all, it is not recommended to use the Android version of this algorithm (in the Android device is very efficient, a figure of about 80 seconds), if it is necessary to use, lowpoly this module into your project can be.

It is recommended to use [this library](https://github.com/zzhoujay/LowPoly) to return to the Android side after the server is generated

**Comment by liwayping** [comment]
Thank you for sharing this library to us, but I think it too slowly to accept! @zzhoujay

**Comment by zzhoujay** [comment]
确实，其实本来就不推荐直接在Android设备上直接进行此类图片的处理，合理的做法是将这些处理交给服务端，README上已经提到了，你需要看这个：[LowPoly](https://github.com/zzhoujay/LowPoly)，你可以把这个集成在你的服务端里 @way1989
